# -*- coding: utf-8 -*-
"""
Created on Fri Oct 18 09:12:22 2019
@author: NINIC2

DESCRIPTION: THE FOLLOWING SCRIPT CAN BE USED TO READ A DATA FILE GENERATED BY THE TRESCON INSTRUMENT
IT WILL AUTOMATICALLY SET THE DATATIME IN THE CORRECT FORMAT

Copyright (c) 2019 by Niels Nicolaï, nicolai.niels@gmail.com, modelEAU, Université Laval. All Rights Reserved.
"""

import pandas as pd

#Specify the file path. Either relative to this python script or absolute
file_path = 'October/trescon_20191010-14.csv'

df_tres = pd.read_csv(file_path, sep=',')
df_tres['datetime'] = pd.to_datetime(df_tres['datetime'],dayfirst = True)
df_tres.set_index('datetime', drop=True, inplace=True)

#Merge this dataframe with another one
df_final = df.join(df_tres, how='outer')

#Saves the final dataset in a CSV file
df_final.to_csv('October/alldata_20191018.csv')